- src/TimeseriesComponent/TimeseriesComponent.js
This adds zooming by default. Will later be refined to be configurable, also separately for x/y direction.
@KaiVolland Please review.
> Add zooming

- .babelrc
- .gitignore
- README.md
- package.json
- src/AxesUtil/AxesUtil.js
- src/BarComponent/BarComponent.js
- src/BaseUtil/BaseUtil.js
- src/ChartDataUtil/ChartDataUtil.js
- src/ChartRenderer/ChartRenderer.js
- src/LabelUtil/LabelUtil.js
- src/LegendComponent/LegendComponent.js
- src/ScaleUtil/ScaleUtil.js
- src/TimeseriesComponent/TimeseriesComponent.js
- src/index.js
- webpack.config.js
This adds a lot of new functionality:
* support for grouped bar charts
* lots of improvements for timeseries charts: can now do (almost?) anything that https://github.com/OpenBfS/gis-client can do
* legend rendering
* improvements of node setup (notably runs with babel v7, a dev build in `package.json` etc.)
* automated layout
It's still in an early state, but it's getting there.
> Charting improvements

- src/AxesUtil/AxesUtil.js
- src/BarComponent/BarComponent.js
- src/TimeseriesComponent/TimeseriesComponent.js
This includes:
* bugfix to prevent crash in case of missing line chart values
* prevent label padding if no label is configured for y axes
* properly center the title in bar charts
> Various fixes

- src/AxesUtil/AxesUtil.js
- src/AxesUtil/AxesUtil.spec.js
- src/ChartRenderer/ChartRenderer.spec.js
- src/LegendComponent/LegendComponent.spec.js
- src/index.spec.js
> Adds a couple of tests

- src/LegendComponent/LegendComponent.js
> Take legend icon width into account

- src/BarComponent/BarComponent.js
This fixes the range of the x scales wrt the available space and calculates the proper size of the bar chart svg.
> Fix bar chart positioning/sizing

- src/AxesUtil/AxesUtil.js
> Wraps x axis labels

- src/AxesUtil/AxesUtil.js
- src/ChartRenderer/ChartRenderer.js
- src/LegendComponent/LegendComponent.js
- src/ScaleUtil/ScaleUtil.js
- src/TimeseriesComponent/TimeseriesComponent.js
Also fixes a bug with `undefined` tick config options.
> Adds workarounds for older babel versions

- package.json
> chore(package): update d3 to version 5.9.1

- src/BarComponent/BarComponent.js
> Always render below threshold labels at the bottom

- browser-build.config.js
> Fix browser build

- src/BaseUtil/BaseUtil.ts
- src/LabelUtil/LabelUtil.ts
> Adds a parameter to limit the title length

- src/TimeseriesComponent/TimeseriesComponent.ts
> Consider custom stroke/fill parameters from style object

- src/AxesUtil/AxesUtil.ts
> Fix rendering of y axis for bar charts

- src/BarComponent/BarComponent.ts
> Add below-threshold / above-threshold class to bar chart label

- src/AxesUtil/AxesUtil.ts
- src/LegendComponent/LegendComponent.ts
- src/ScaleUtil/ScaleUtil.ts
- src/TimeseriesComponent/TimeseriesComponent.ts
This adds several imporvements to the display of logarithmic scales:
- Throw on invalid configs
- Adds harmonization to AxesUtil
- Makes epsilon configurable
> Enhancements for logarithmic scales

- src/AxesUtil/AxesUtil.ts
This introduces a `tickFormatter` config to allow the usage of a custom tickFormatter.
> Introduces custom tickFormatter

- src/BarComponent/BarComponent.ts
- src/TimeseriesComponent/TimeseriesComponent.ts
Sets the background color on the svg element if configured.
> Add background color to the svg element

- .ok.fish
- README.md
- src/LegendComponent/LegendComponent.ts
Adds `onHover` and `onMouseOut` configs for legend items.
> Add hover and mouseout configs

- src/TimeseriesComponent/TimeseriesComponent.ts
- tslint.json
Fixes setting the initial y axis zoom.
> Fix initial y axis zoom

- src/BarComponent/BarComponent.ts
> Fix IE11 compatibility

- package-lock.json
- package.json
- src/TimeseriesComponent/TimeseriesComponent.ts
- src/TimeseriesComponent/index.d.ts
Fixes issues when zooming only on one axis, then the others since the original d3-zoom package only allows a single scale value in the zoom transform.
Using https://github.com/wiremind/d3-xyzoom this issue is fixed by using two different scale values in the transform.
> Fix xy zoom

- README.md
- src/AxesUtil/AxesUtil.ts
> Change axis format parameter to accept arrays instead of json string

- package-lock.json
- package.json
- src/TimeseriesComponent/TimeseriesComponent.ts
> Cleanup initial zoom handling

- README.md
- src/AxesUtil/AxesUtil.ts
- src/ChartRenderer/ChartRenderer.ts
- src/TimeseriesComponent/TimeseriesComponent.ts
This
* renames `eventFn` to `onMouseMoveFunc`
* fixes the computation for the xAxis label position
* adds supporting custom format functions on the axis config `format` property
> Fix xAxis label + add format function + rename eventFn

- src/AxesUtil/AxesUtil.ts
- src/TimeSelectComponent/TimeSelectComponent.ts
* enhanced utility method to aso handle x-axes
* format axes tick labels based on resolution and duration
@terrestris/devs please review
> Better display of x-axis tick values in TimeSelectComponent

- src/TimeSelectComponent/TimeSelectComponent.ts
> Fix creating new selection

- .github/workflows/on-pull-request.yml
- jest.config.js
> Use proper test environment

- src/TimeSelectComponent/TimeSelectComponent.ts
> Add tooltips for time range selection chart

- src/TimeSelectComponent/TimeSelectComponent.ts
> Configurable x domain
